server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      #uri: mongodb://microservice-mongo5:27017/db_bootcamp
      uri: mongodb://localhost:27017/db_bootcamp

eureka:
  client:
    serviceUrl:
      #defaultZone: http://servicio-eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

endpoint:
  #productBank: http://microservice-gateway:8090/api/productBank
  productBank: http://localhost:8090/api/productBank
  #client: http://microservice-gateway:8090/api/client
  client: http://localhost:8090/api/client