server:
  port: 8005

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_bootcamp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

endpoint:
  productBank: http://localhost:8003/productBank
  client: http://localhost:8002/client