server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      uri: mongodb://microservice-mongo5:27017/db_bootcamp

eureka:
  client:
    serviceUrl:
      defaultZone: http://servicio-eureka-server:8761/eureka