server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      #uri: mongodb://microservice-mongo5:27017/db_bootcamp
      uri: mongodb://localhost:27017/db_bootcamp

eureka:
  client:
    serviceUrl:
      #defaultZone: http://servicio-eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka

endpoint:
  #productBank: http://microservice-gateway:8090/api/productBank
  productBank: http://localhost:8090/api/productBank
  #client: http://microservice-gateway:8090/api/client
  client: http://localhost:8090/api/client

resilience4j:
  retry:
    retry-aspect-order: 2
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      myCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60