server:
  #port: ${PORT:0}
  port: 9004

spring:
  data:
    mongodb:
      #uri: mongodb://microservice-mongo5:27017/db_bootcamp
      uri: mongodb://localhost:27017/db_bootcamp

eureka:
  client:
    serviceUrl:
      #defaultZone: http://servicio-eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka

endpoint:
  #productBank: http://microservice-gateway:8090/api/productBank
  #productBank: http://localhost:8090/api/productBank
  productBank: http://localhost:9002/productBank
  #client: http://microservice-gateway:8090/api/client
  #client: http://localhost:8090/api/client
  client: http://localhost:9003/client

resilience4j:
  circuitbreaker:
    instances:
      customerContactInfoService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        timeoutDuration: 2s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always